---
abstract: 'Time line represented as an object'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Timeline
provides:
  Data::Timeline:
    file: lib/Data/Timeline.pm
    version: 1.100850
  Data::Timeline::Builder:
    file: lib/Data/Timeline/Builder.pm
    version: 1.100850
  Data::Timeline::Entry:
    file: lib/Data/Timeline/Entry.pm
    version: 1.100850
  Data::Timeline::Formatter:
    file: lib/Data/Timeline/Formatter.pm
    version: 1.100850
  Data::Timeline::Formatter::HTML:
    file: lib/Data/Timeline/Formatter/HTML.pm
    version: 1.100850
  Data::Timeline::Formatter::SimpleTable:
    file: lib/Data/Timeline/Formatter/SimpleTable.pm
    version: 1.100850
requires:
  Carp: 0
  Class::Accessor::Complex: 0
  Class::Accessor::Constructor: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  HTML::Table: 0
  Scalar::Util: 0
  Test::More: 0.88
  Text::SimpleTable: 0
  parent: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Data-Timeline
  homepage: http://search.cpan.org/dist/Data-Timeline/
  repository: http://github.com/hanekomu/Data-Timeline
version: 1.100850
